export { Home } from './home/index'
export { ComingSoon } from './coming-soon/index'
export { Marketplace } from './marketplace/index'
export { NftAuctions } from './nft-auctions/index'
export { NftStaking } from './nft-staking/index'
export { Portfolio } from './portfolio/index'
export { NFTAuctionDetails } from './nft-auction-details/index'
export { MarketplaceDetails } from './marketplace-details/index'
